apiVersion: apps/v1
kind: Deployment
metadata:
  name: ciflowx-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: ciflowx-app
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 0
      maxSurge: 1
  template:
    metadata:
      labels:
        app: ciflowx-app
    spec:
      containers:
        - name: ciflowx-app
          image: harvansh1/ciflowx-app:latest
          ports:
            - containerPort: 3000
          readinessProbe:
            httpGet:
              path: /health
              port: 3000
            initialDelaySeconds: 5
            periodSeconds: 5
          livenessProbe:
            httpGet:
              path: /health
              port: 3000
            initialDelaySeconds: 10
            periodSeconds: 10